version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_employee_management
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_employee_management
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
    driver: local